name: Deploy to GitHub Pages

on:
  push:
    branches:
      - prod
      - PE-5161_gift_app_init

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn --immutable --immutable-cache

      - name: Build
        run: yarn build

      - name: Copy index.html to 404.html
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy gh-pages if on prod
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
